name:                ProtoHaskell
version:             0.1.0.0
github:              "JKTKops/ProtoHaskell"
license:             BSD3
author:              "Max Kopinsky"
maintainer:          "zerglingk9012@gmail.com"
copyright:           "2019 Max Kopinsky"

extra-source-files:
- README.md
- ChangeLog.md
- src/Compiler/Parser/Lexer.x

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JKTKops/ProtoHaskell#readme>

default-extensions:
- ApplicativeDo
- BangPatterns
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- PatternGuards
- TupleSections
- ViewPatterns

dependencies:
- array
- base >= 4.7 && < 5
- containers
- mtl
- parsec
- pretty
- text

library:
  source-dirs: src

executables:
  phc:
    main:                Main.hs
    source-dirs:         app

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ProtoHaskell

tests:
  phc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ProtoHaskell
